[package]
name = "game-server"
version = "0.1.0"
authors = []
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"
byte = "0.2.4"
once_cell = "1.4.1"
lazy_static = "1.4.0"